
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/
export const USER_ROLE = {
  ADMIN: 'ADMIN',
  USER: 'USER'
} as const

export type USER_ROLE = (typeof USER_ROLE)[keyof typeof USER_ROLE]


export const DIFFICULTY = {
  EASY: 'EASY',
  MEDIUM: 'MEDIUM',
  HARD: 'HARD'
} as const

export type DIFFICULTY = (typeof DIFFICULTY)[keyof typeof DIFFICULTY]


export const LANGUAGE = {
  PYTHON: 'PYTHON',
  JAVASCRIPT: 'JAVASCRIPT'
} as const

export type LANGUAGE = (typeof LANGUAGE)[keyof typeof LANGUAGE]
